import { Router } from "express";
import passport from "passport";

import { config } from "../config/app.config.js";
import { handleGoogleAuthSuccess, registerUser } from "../controllers/auth.controller.js";

const authRoutes = Router();

// auth/google
authRoutes.route("/google").get(
    passport.authenticate("google", {
        scope: ["profile", "email"],
    }),

    /*
    What Happains B.T.S ?

        Step 0: Strategy Lookup
            - passport.authenticate("google")
            - Fetches pre-configured GoogleStrategy from :
                passport._strategies["google"]

        Step 1: Delegate to Strategy
            - Calls:
                strategy.authenticate(req, options)

        Step 2: Detect Flow Type
            - No "code" in request => Initial OAuth request
            - Decision: Redirect user to Google

        Step 3: Load Config (from strategy instance)
            | Field           | Value Source                                                                                           |
            | --------------- | ------------------------------------------------------------------------------------------------------ |
            | `client_id`     | From `passport.use(new GoogleStrategy({ clientID }))`                                                  |
            | `redirect_uri`  | From `passport.use(new GoogleStrategy({ callbackURL }))` - `<backend_origin>/api/auth/google/callback` |
            | `scope`         | From `passport.authenticate("google", { scope: [...] })`                                               |
            | `response_type` | Fixed by OAuth flow - `"code"` (Authorization Code Flow)                                               |
            | `state`         | Auto-generated by Passport (CSRF protection token)                                                     |

        Step 4: Construct Authorization URL
            - const authorizationURL =
            "https://accounts.google.com/v3/signin/accountchooser?" +
            querystring.stringify({
                client_id: strategy._oauth2._clientId,
                redirect_uri: strategy._callbackURL,
                response_type: "code",
                scope: "profile email",
                state: generatedState
            });

        Step 5: Redirect to Google
            - res.redirect(authorizationURL)
            - Browser navigates to Google Authorization Screen

        Step 6: Consent Decision
            - User is asked:
            - Allow access to:
                - Profile info
                - Email address

        Two Possible Paths
            - ✔️ User Clicks "Allow"
                - Redirect To : <backend_origin>/api/auth/google/callback?code=AUTH_CODE
            - ⛔ User Clicks "Deny"
                - Redirect To : <backend_origin>/api/auth/google/callback?error=access_denied
    */
);

authRoutes.route("/google/callback").get(
    passport.authenticate("google", {
        session: true,
        failureRedirect: `${config.get_FRONTEND_GOOGLE_CALLBACK_URL()}?status=failure`,
    }),
    handleGoogleAuthSuccess,

    /*
    What Happains B.T.S ?
        ✔️ User Clicks "Allow"
            - Redirect To : <backend_origin>/api/auth/google/callback?code=AUTH_CODE

        Step 7: Detect code in query
            - req.query.code !== undefined
            - Decides:
                - Skip authorization URL Creation
                - Start token exchange

        Step 8: Exchange Code => Tokens
            - POST https://oauth2.googleapis.com/token
                - Payload
                | Field           | Value Source                                                       |
                | --------------- | ------------------------------------------------------------------ |
                | `client_id`     | configured during - passport.use(new GoogleStrategy( {......})     |
                | `client_secret` | configured during - passport.use(new GoogleStrategy( {......})     |
                | `code`          | from `req.query.code`                                              |
                | `redirect_uri`  | configured during - passport.use(new GoogleStrategy( {......})     |
                | `grant_type`    | `"authorization_code"`                                             |

        Step 9: Google Responds
            - Response Example
                {
                    "access_token": "...",
                    "refresh_token": "...",
                    "id_token": "...",
                    "expires_in": 3599
                }

        Step 10: Fetch User Profile
            - GET https://www.googleapis.com/oauth2/v2/userinfo
            - Authorization: Bearer ACCESS_TOKEN

            - Profile Example:
                {
                    id: "google-id",
                    displayName: "User Name",
                    emails: [{ value: "user@gmail.com" }],
                    photos: [...]
                }

        Step 11: Call googleVerifyCallback function
            - googleVerifyCallback(req, accessToken, refreshToken, profile, done)
                * configured during - passport.use(new GoogleStrategy( {......})
            - Now 2 paths :
                Path A : done(null, user);
                    - this.success(user, info);
                    - req.user = user (temporary (request-scoped))
                    - res.login(user) [ As session:true ]

                Path B : done(error, false);
                    - Authentication failed
                    - this.error(error);
                    - error is forwarded to Express error pipeline : if (err) return next(err);

        Step 12: Passport calls res.login(user) automatically [ As session:true ]
            - req.login() method set by `passport.initialize()` Middleware
            - Internally:
                - serializeUser(user, done)
                - done(null, user._id)
                - req.session.passport = { user: user.id }
                - req.session.save()

            - Cookie behavior:
                - express-session - only sessionId sent
                - actual data stored in server session store

        Step 13: Passport finishes its job
            - calls next()
            - control move to handleGoogleAuthSuccess Controller

            Step 14: handleGoogleAuthSuccess Controller
            - req.user              // ✅ full user object ((current request))
            - req.session           // ✅ contains passport.user (USER_ID)
            - req.isAuthenticated() // ✅ true


        ===============================================================================================

        ⛔ User Clicks "Deny"
            - Redirect To : <backend_origin>/api/auth/google/callback?error=access_denied

        Step 7: Check Query Param
            - req.query.param === "access_denied"

        Step 8: Immediate Failure Trigger
            - Strategy does NOT:
                - ⛔ exchange code
                - ⛔ call Google token API
                - ⛔ call your verifyCallback
            - return this.fail({ message: "access_denied" });

        Step 9: Redirect to failureRedirect
            - res.redirect(`${config.get_FRONTEND_GOOGLE_CALLBACK_URL()}?status=failure`)

        ===============================================================================================
    */
);

authRoutes.route("/register").post(registerUser);

// app.post("/logout", (req, res, next) => {
//   req.logout(function (err) {
//     if (err) return next(err);

//     req.session = null;
//     res.redirect("/login");
//     res.status(200).json({ message: "Logged out" });
//
//   });
// });
//
// router.post("/logout", (req, res, next) => {
//   req.logout(function (err) {
//     if (err) return next(err);

//     req.session.destroy((err) => {
//       if (err) return next(err);

//       res.clearCookie("to-session");
//       res.status(200).json({ message: "Logged out successfully" });
//     });
//   });
// });

export default authRoutes;

// res.logout()
// - Removes req.user
// - Clears Passport session data (passport.user)

// req.session.destroy()
// - Deletes session from store (MemoryStore / Redis)
// - Invalidates session ID

// res.clearCookie()
// Removes session cookie from Browser
// Prevents reuse of old sessionId
